import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./../global.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Baseel nextjs assessment",
  description: "Generated by baseel nextjs assessment",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navbar />
        <ToastContainer theme="dark" hideProgressBar={false} />
        {children}
      </body>
    </html>
  );
}